In [1]:
from PIL import Image
from scipy.io import loadmat
import numpy as np
from pathlib import Path
from tqdm import tqdm
import itertools
from scipy.ndimage.morphology import distance_transform_edt
from collections import Counter
from itertools import chain
import json

from utils.show import show_layers_from_mask, show_layers_from_boundary

                        
def boundary_length_distribution(folder):
    lengths = []
    for file in folder:
        data = loadmat(file)
        for bscan in data["layerMaps"]:
            x_inds, _ = np.where(~np.isnan(bscan))
            if x_inds.any():
                lengths.append(x_inds[-1] - x_inds[0])
    return lengths


def boundary_middle_distribution(folder):
    middles = []
    for file in folder:
        data = loadmat(file)
        for bscan in data["layerMaps"]:
            x_inds, _ = np.where(~np.isnan(bscan))
            if x_inds.any():
                middles.append(x_inds[len(x_inds) // 2])
    return middles

# Data generation

In [73]:
def create_patches(img, lyr, patch_width):
    idx = np.where((np.isnan(lyr)).any(axis=0))[0]
    diff = np.diff(idx)
    useful_parts = diff >= patch_width
    useful_lengths = diff[useful_parts]
    useful_start_idx = idx[np.pad(useful_parts, (0, 1), constant_values=[False])]
    for ustart, ulength in zip(useful_start_idx, useful_lengths):
        number_of_shifts = (ulength - 1) // patch_width
        for shift_idx in range(number_of_shifts):
            img_patch = img[:, ustart + 1 + shift_idx * patch_width:ustart + 1 + (shift_idx + 1) * patch_width]
            lyr_patch = lyr[:, ustart + 1 + shift_idx * patch_width:ustart + 1 + (shift_idx + 1) * patch_width]
            mask = create_layer_mask(lyr_patch, img_patch.shape[0])
            yield img_patch, mask
            
def generate_dme_dataset(input_dir, output_dir, patch_width):
    files = list(Path(input_dir).glob("*"))
    output_dir = Path(output_dir)
    output_dir.mkdir()
    cnt = 0
    for file in tqdm(files, desc="data generation"):
        data = loadmat(file)
        layers = data["manualLayers1"].transpose((2, 0, 1))
        images = data["images"].transpose((2, 0, 1))
        for idx, (image, layer) in enumerate(zip(images, layers)):
            patch_generator = create_patches(image, layer, patch_width)
            for img, mask in patch_generator:
                Image.fromarray(img).save(output_dir / f"img_{cnt}.png")
                Image.fromarray(mask).save(output_dir / f"mask_{cnt}.png")
                cnt += 1
                
def create_boundary_mask(boundary_array, height):
    mask = np.zeros((height, boundary_array.shape[1]), dtype="uint8")
    for col_idx, col in enumerate(boundary_array.T):
        if ~np.isnan(col).any():
            for boundary in col:
                mask[int(boundary), col_idx] = 1
    return mask

def create_layer_mask(boundary_array, height, fluid=None):
    mask = np.zeros((height, boundary_array.shape[1]), dtype="uint8")
    for col_idx, col in enumerate(boundary_array.T):
        prev_boundary = 0
        for boundary_idx, boundary in enumerate(col):
            mask[prev_boundary:int(boundary) + 1, col_idx] = boundary_idx
            prev_boundary = int(boundary) + 1
        mask[prev_boundary:, col_idx] = boundary_idx + 1
    fluid_class = len(col) + 1
    if isinstance(fluid, np.ndarray):
        mask[fluid != 0] = fluid_class
    return mask

def create_patches(img, lyr, patch_width, fluid):
    idx = np.where((np.isnan(lyr)).any(axis=0))[0]
    diff = np.diff(idx)
    useful_parts = diff >= patch_width
    useful_lengths = diff[useful_parts]
    useful_start_idx = idx[np.pad(useful_parts, (0, 1), constant_values=[False])]
    for ustart, ulength in zip(useful_start_idx, useful_lengths):
        number_of_shifts = (ulength - 1) // patch_width
        for shift_idx in range(number_of_shifts):
            indices = (slice(None), slice(
                ustart + 1 + shift_idx * patch_width, ustart + 1 + (shift_idx + 1) * patch_width
            ))
            img_patch = img[indices]
            lyr_patch = lyr[indices]
            fluid_patch = fluid[indices] if isinstance(fluid, np.ndarray) else fluid
            mask = create_layer_mask(lyr_patch, img_patch.shape[0], fluid_patch)
            yield img_patch, mask, lyr_patch.T.tolist()
            
def generate_dme_dataset(input_dir, output_dir, patch_width, use_fluid=False):
    files = list(Path(input_dir).glob("*"))
    output_dir = Path(output_dir)
    output_dir.mkdir()
    cnt = 0
    boundary_indices_dict = {}
    layer_widths_dict = {}
    for file in tqdm(files, desc="data generation"):
        data = loadmat(file)
        layers = data["manualLayers1"].transpose((2, 0, 1))
        images = data["images"].transpose((2, 0, 1))
        fluids = data["manualFluid1"].transpose((2, 0, 1))
        for idx, (image, layer, fluid) in enumerate(zip(images, layers, fluids)):
            fluid = fluid if (~np.isnan(fluid)).any() and use_fluid else None 
            patch_generator = create_patches(image, layer, patch_width, fluid)
            for img, mask, boundary_indices_list in patch_generator:
                Image.fromarray(img).save(output_dir / f"img_{cnt}.png")
                Image.fromarray(mask).save(output_dir / f"mask_{cnt}.png")
                boundary_indices_dict[cnt] = boundary_indices_list
                cnt += 1
    with open(output_dir / "boundary_indices.json", "w") as boundary_file:
        json.dump(boundary_indices_dict, boundary_file)

# LOAD FILES

In [3]:
amd = list(Path("../../dataset/raw/AMD/").glob("*"))
control = list(Path("../../dataset/raw/Control/").glob("*"))
dme = list(Path("../../dataset/raw/2015_BOE_Chiu/").glob("*"))

# Test new concept

In [124]:
x = torch.tensor([1, 0, -1, 0, 1, 0, -1, -1])

In [125]:
len(x) - x.flip(0).min(0).indices - 1 - x.max(0).indices

tensor(7)

In [58]:
a[(slice(1, 3), slice(None))]

array([[-0.30493972, -1.38685806, -0.25046206, -1.66599754,  0.90199246,
        -0.27416333, -0.62988202, -0.68810881, -0.88376661,  0.36708645],
       [ 0.3900947 , -0.74614864, -0.24758149,  0.44142163,  0.00417762,
         0.38001564, -0.5956527 ,  0.57951245,  1.44324228,  0.51722583]])

# DME

In [4]:
data = loadmat(dme[2])

In [5]:
np.where((~np.isnan(data["manualFluid1"])).any(axis=(0, 1)))

(array([10, 15, 20, 25, 28, 30, 32, 35, 40, 45, 50]),)

In [81]:
idx = 10
img = data["images"][..., idx]
lyr = data["manualLayers1"][..., idx]
fluid = data["manualFluid1"][..., idx]

In [12]:
lyr.shape

(8, 768)

In [79]:
def show_layers_from_boundary(img_array, layer_array, mean_std=None, a_scan_length=496, fluid=None, normed=False):
    err_msg = "layer boundaries not compatible with image width"
    assert img_array.shape[1] == layer_array.shape[1], err_msg
    if type(img_array) == torch.Tensor:
        img_array = img_array.numpy()
    if type(layer_array) == torch.Tensor:
        layer_array = layer_array.numpy()
    if mean_std:
        img_array = img_array * mean_std[1] + mean_std[0]
        layer_array = layer_array * mean_std[3] + mean_std[2]
    if normed:
        img_array = np.asarray(img_array * 255, "uint8")
        layer_array = np.asarray(layer_array * a_scan_length, "uint8")
    dme_colorcode = {
        1: (170, 160, 250),
        2: (120, 200, 250),
        3: (80, 200, 250),
        4: (50, 230, 250),
        5: (20, 230, 250),
        6: (0, 230, 250),
        7: (0, 230, 100),
        8: (180, 255, 255)  # fluid
    }
    amd_colorcode = {
        1: (180, 200, 250),
        2: (120, 200, 250),
    }
    zeros = np.zeros_like(img_array, dtype="uint8")
    hue = np.zeros_like(img_array, dtype="uint8")
    saturation = np.zeros_like(img_array, dtype="uint8")
    value = np.zeros_like(img_array, dtype="uint8")
    mask = np.zeros(img_array.shape, dtype="uint8")
    layer_array = layer_array.T
    for w in range(img_array.shape[1]):
        if ~np.isnan(layer_array[w, :]).any():
            last_boundary = int(layer_array[w, 0])
            for idx, h in enumerate(layer_array[w, 1:]):
                curr_boundary = int(h) + 1
                mask[last_boundary:curr_boundary, w] = idx + 1
                last_boundary = curr_boundary
    if fluid is not None:
        mask[fluid != 0] = 8
    if layer_array.shape[1] == 8:
        for klass, hsv in dme_colorcode.items():
            hue[mask == klass] = hsv[0]
            saturation[mask == klass] = hsv[1]
            value[mask == klass] = hsv[2]
    if layer_array.shape[1] == 3:
        for klass, hsv in amd_colorcode.items():
            hue[mask == klass] = hsv[0]
            saturation[mask == klass] = hsv[1]
            value[mask == klass] = hsv[2]
    alpha = np.zeros_like(img_array, dtype="uint8")
    alpha[mask != 0] = 255
    img_stack = np.array([zeros, zeros, img_array]).transpose((1, 2, 0))
    img = Image.fromarray(img_stack, mode="HSV")
    colored_mask_stack = np.array([hue, saturation, value]).transpose((1, 2, 0))
    colored_mask = Image.fromarray(colored_mask_stack, mode="HSV")
    alphaimg = Image.fromarray(alpha)
    img_with_boundaries = Image.composite(colored_mask, img, alphaimg)
    return img_with_boundaries

In [84]:
import torch
from utils.data import OCTDataset

In [82]:
show_layers_from_boundary(img, lyr, normed=False, fluid=fluid).show()

In [85]:
ds = OCTDataset("../../generated/fluid/training/DME_64")

In [99]:
for i in range(len(ds)):
    x, y = ds[i]
    if y.max() == 9:
        print(i)

24
25
26
32
33
38
39
44
45
58
59
66
67
73
74
75
93
96
99
100
104
109
112
113
116
117
118
129
130
137
138
151
156
157
158
159
160
163
167
170
173
174
179
180
218
224
244
282
283
287
288
289
290
291
294
295
296
299
300
302
307
311
317
318
323
324
325


In [106]:
idx = 317
show_layers_from_mask(ds[idx][0], ds[idx][1], normed=True).show()

In [24]:
data["manualFluid1"].shape

(496, 768, 61)

In [22]:
a = np.array([np.nan, np.nan])

In [7]:
idx = 12
img = np.array(Image.open(f"../../generated/DME_496/img_{idx}.png"))
lyr = np.array(Image.open(f"../../generated/DME_496/mask_{idx}.png"))

In [8]:
show_layers_from_mask_array(img, lyr).show()

In [13]:
show_layers_from_boundary_array(img, lyr2.T).show()
show_layers_from_boundary_array(img, lyr.T).show()

In [320]:
data = loadmat("../../dataset/raw/2015_BOE_Chiu/Subject_02.mat")

In [321]:
idx = 28

In [322]:
img = data["images"][..., idx]
lyr = data["manualLayers1"][..., idx]

In [323]:
show_layers_from_boundary_array(img, lyr.T).show()

In [65]:
segmented_length = list()

for d in range(10):
    data = loadmat(dme[d])
    for lyr_ind in range(61):
        m1 = data["manualLayers1"][..., lyr_ind]
        m2 = data["manualLayers2"][..., lyr_ind]
        lengths = [] 
        if (~np.isnan(m1)).any():
            w_idx = np.where(~np.isnan(m1))[1]
            delta = w_idx[-1] - w_idx[0]
            lengths.append(delta)
        else:
            lengths.append(0)
        if (~np.isnan(m2)).any():
            w_idx = np.where(~np.isnan(m2))[1]
            delta = w_idx[-1] - w_idx[0]
            lengths.append(delta)
        else:
            lengths.append(0)
        if sum(lengths):
            segmented_length.append(tuple(lengths))
            
Counter(segmented_length)

Counter({(523, 523): 33,
         (547, 547): 11,
         (535, 535): 11,
         (541, 541): 33,
         (505, 505): 11,
         (499, 499): 11})

In [5]:
dme496img = sorted(list(Path("../../generated/DME_496/").glob("img*")))
dme496mask = sorted(list(Path("../../generated/DME_496").glob("mask*")))

In [6]:
img = np.array(Image.open(dme496img[0]))
mask = np.array(Image.open(dme496mask[0]))

In [8]:
show_layers_from_mask_array(img, mask).show()

# There are parts where not all the layers are annotated

In [6]:
# for d in range(10):
#     data = loadmat(dme[d])
#     lyr = data["manualLayers1"]
#     if (np.isnan(lyr).any(axis=0) != np.isnan(lyr).all(axis=0)).sum():
#         print(d)

data = loadmat(dme[0])
lyr = data["manualLayers1"]
img = data["images"]
idx = (np.isnan(lyr).any(axis=0) != np.isnan(lyr).all(axis=0))
np.isnan(lyr[:, idx]).sum(axis=-1)

array([  0,   0,   0,   0, 127,   0,   0,   0])

# Generating the dataset

In [76]:
patch_width = 64
fluid = True
generate_dme_dataset("../../dataset/raw/1-5", f"../../generated{'/fluid' if fluid else ''}/training/DME_{patch_width}", patch_width, use_fluid=True)
generate_dme_dataset("../../dataset/raw/6-10", f"../../generated{'/fluid' if fluid else ''}/validation/DME_{patch_width}", patch_width, use_fluid=True)
len(list(Path(f"../../generated/DME_{patch_width}").glob("img*")))

data generation: 100%|██████████| 5/5 [00:10<00:00,  2.14s/it]


682

In [68]:
a = np.array([M, None])
b = a if a == None

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

# Proove that the layer mask generation is correct

In [354]:
bmask = create_boundary_mask(lyr[:, 500:600], 496)
lmask = create_layer_mask(lyr[:, 500:600], 496)
diff = np.diff(lmask, axis=0)
(np.pad(diff, ((0, 1), (0, 0)), constant_values=(0,)) != bmask).sum()

# AMD

In [10]:
data = loadmat(amd[0])
idx = 30
img = data["images"][:, :, idx]
lyr = data["layerMaps"][idx]

In [14]:
def generate_amd_dataset(amd_dir, control_dir, output_dir, patch_width):
    files = list(
        chain(
            Path(amd_dir).glob("*"),
            Path(control_dir).glob("*")
        )
    )
    output_dir = Path(output_dir)
    output_dir.mkdir()
    cnt = 0
    for file in tqdm(files, desc="data generation"):
        data = loadmat(file)
        layers = data["layerMaps"].transpose((0, 2, 1))
        images = data["images"].transpose((2, 0, 1))
        for idx, (image, layer) in enumerate(zip(images, layers)):
            patch_generator = create_patches(image, layer, patch_width)
            for img, mask in patch_generator:
                Image.fromarray(img).save(output_dir / f"img_{cnt}.png")
                Image.fromarray(mask).save(output_dir / f"mask_{cnt}.png")
                cnt += 1

In [34]:
patch_width = 736
generate_amd_dataset(
    "../../dataset/raw/AMD/",
    "../../dataset/raw/Control/",
    f"../../generated/AMD_{patch_width}",
    patch_width
)

data generation: 100%|██████████| 384/384 [04:31<00:00,  1.42it/s]


In [35]:
len(list(Path("../../generated/AMD_736").glob("img*")))

2901

In [26]:
loadmat(d)

784

In [33]:
736 / 16

46.0

In [11]:
show_layers_from_boundary_array(img, lyr).show()
show_boundary_from_boundary_array(img, lyr).show()